### ISSUE TITLE
[误杀] ip2location.com

### ISSUE THREAD

**Issue by Myer921** [privacy-protection-tools/anti-AD#163]
域名：ip2location.com
发生时间：2020年06月30日
问题描述：

这是一个 ip 库有关的网站，不知为何被误杀，我还看到一些被误杀的对象，我会随时编辑

**Comment by Myer921** [comment]
https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-domains.txt#L18454

ip138 和 ip2location.com 被误杀

**Comment by sr093906** [comment]
@gentlyxu Rather than simply removing such positioning services and websites from blacklist, I suggest creating an aggressive version to put such controversial domains. Some users do not care exposing their IP to apps even when location function of smart phone was disabled, but others are not willing to do so… Why should the apps know where I am to work ?

**Comment by gentlyxu** [comment]
> @gentlyxu Rather than simply removing such positioning services and websites from blacklist, I suggest creating an aggressive version to put such controversial domains. Some users do not care exposing their IP to apps even when location function of smart phone was disabled, but others are not willing to do so… Why should the apps know where I am to work ?

谢谢你的建议，收到了

**Comment by JuneOx** [comment]
news.163.com中要闻等无法访问
