### ISSUE TITLE
[误杀] 小米社区图片CDN

### ISSUE THREAD

**Issue by PussAzuki** [privacy-protection-tools/anti-AD#556]
域名：cdn.cnbj1.fds.api.mi-img.com
发生时间：2022年01月18日
使用的列表：https://anti-ad.net/anti-ad-for-dnsmasq.conf
问题描述：忽然发现小米社区头像和图片加载不出来了

**Comment by fernvenue** [comment]
That's true, same thing happened in [this app](https://apps.apple.com/us/app/id1024958046), maybe allow `*.mi-img.com` is a good choice, that works for me. And this also means that there may be image loading issues caused by blocking these domains in other Xiaomi applications or services that we have not been tested yet.
